# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
  - MAKEFLAGS="-j 2"
  - _R_CHECK_FORCE_SUGGESTS_=false

jobs:
  include:
  - r: devel
  - r: release
  
after_success:
    - Rscript -e 'covr::codecov()'