// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_simcdm_RCPPEXPORTS_H_GEN_
#define RCPP_simcdm_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace simcdm {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("simcdm", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("simcdm", "_simcdm_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in simcdm");
            }
        }
    }

    inline arma::mat sim_dina_class(unsigned int N, unsigned int J, const arma::vec& CLASS, const arma::mat& ETA, const arma::vec& gs, const arma::vec& ss) {
        typedef SEXP(*Ptr_sim_dina_class)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_sim_dina_class p_sim_dina_class = NULL;
        if (p_sim_dina_class == NULL) {
            validateSignature("arma::mat(*sim_dina_class)(unsigned int,unsigned int,const arma::vec&,const arma::mat&,const arma::vec&,const arma::vec&)");
            p_sim_dina_class = (Ptr_sim_dina_class)R_GetCCallable("simcdm", "_simcdm_sim_dina_class");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sim_dina_class(Shield<SEXP>(Rcpp::wrap(N)), Shield<SEXP>(Rcpp::wrap(J)), Shield<SEXP>(Rcpp::wrap(CLASS)), Shield<SEXP>(Rcpp::wrap(ETA)), Shield<SEXP>(Rcpp::wrap(gs)), Shield<SEXP>(Rcpp::wrap(ss)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat sim_dina_attributes(const arma::mat& alphas, const arma::mat& Q) {
        typedef SEXP(*Ptr_sim_dina_attributes)(SEXP,SEXP);
        static Ptr_sim_dina_attributes p_sim_dina_attributes = NULL;
        if (p_sim_dina_attributes == NULL) {
            validateSignature("arma::mat(*sim_dina_attributes)(const arma::mat&,const arma::mat&)");
            p_sim_dina_attributes = (Ptr_sim_dina_attributes)R_GetCCallable("simcdm", "_simcdm_sim_dina_attributes");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sim_dina_attributes(Shield<SEXP>(Rcpp::wrap(alphas)), Shield<SEXP>(Rcpp::wrap(Q)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat sim_dina(const arma::mat& alphas, const arma::mat& Q, const arma::vec& ss, const arma::vec& gs) {
        typedef SEXP(*Ptr_sim_dina)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_sim_dina p_sim_dina = NULL;
        if (p_sim_dina == NULL) {
            validateSignature("arma::mat(*sim_dina)(const arma::mat&,const arma::mat&,const arma::vec&,const arma::vec&)");
            p_sim_dina = (Ptr_sim_dina)R_GetCCallable("simcdm", "_simcdm_sim_dina");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sim_dina(Shield<SEXP>(Rcpp::wrap(alphas)), Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(ss)), Shield<SEXP>(Rcpp::wrap(gs)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat sim_rrum_main(const arma::mat& Q, const arma::mat& rstar, const arma::vec& pistar, const arma::mat& alpha) {
        typedef SEXP(*Ptr_sim_rrum_main)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_sim_rrum_main p_sim_rrum_main = NULL;
        if (p_sim_rrum_main == NULL) {
            validateSignature("arma::mat(*sim_rrum_main)(const arma::mat&,const arma::mat&,const arma::vec&,const arma::mat&)");
            p_sim_rrum_main = (Ptr_sim_rrum_main)R_GetCCallable("simcdm", "_simcdm_sim_rrum_main");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sim_rrum_main(Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(rstar)), Shield<SEXP>(Rcpp::wrap(pistar)), Shield<SEXP>(Rcpp::wrap(alpha)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat sim_rrum(const arma::mat& Q, const arma::mat& rstar, const arma::vec& pistar, const arma::mat& alpha) {
        typedef SEXP(*Ptr_sim_rrum)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_sim_rrum p_sim_rrum = NULL;
        if (p_sim_rrum == NULL) {
            validateSignature("arma::mat(*sim_rrum)(const arma::mat&,const arma::mat&,const arma::vec&,const arma::mat&)");
            p_sim_rrum = (Ptr_sim_rrum)R_GetCCallable("simcdm", "_simcdm_sim_rrum");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_sim_rrum(Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(rstar)), Shield<SEXP>(Rcpp::wrap(pistar)), Shield<SEXP>(Rcpp::wrap(alpha)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::vec bijectionvector(unsigned int K) {
        typedef SEXP(*Ptr_bijectionvector)(SEXP);
        static Ptr_bijectionvector p_bijectionvector = NULL;
        if (p_bijectionvector == NULL) {
            validateSignature("arma::vec(*bijectionvector)(unsigned int)");
            p_bijectionvector = (Ptr_bijectionvector)R_GetCCallable("simcdm", "_simcdm_bijectionvector");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_bijectionvector(Shield<SEXP>(Rcpp::wrap(K)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::vec >(rcpp_result_gen);
    }

}

#endif // RCPP_simcdm_RCPPEXPORTS_H_GEN_
