# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Binary Responses for a DINA Model
#'
#' Generate the dichotomous item matrix for a DINA Model.
#'
#' @param N     Number of Observations
#' @param J     Number of Assessment Items
#' @param CLASS Does the individual possess all the necessary attributes?
#' @param ETA   \eqn{\eta} Matrix containing indicators.
#' @param gs    A `vec` describing the probability of guessing or
#'              the probability subject correctly answers item \eqn{j} when at
#'              least one attribute is lacking.
#' @param ss    A `vec` describing the probability of slipping or
#'              the probability of an incorrect response for individuals with
#'              all of the required attributes
#'
#' @return A dichotomous item matrix
#' @author Steven Andrew Culpepper and James Joseph Balamuta
#' @template sim-dina-class-example
#' @export
sim_dina_class <- function(N, J, CLASS, ETA, gs, ss) {
    .Call(`_simcdm_sim_dina_class`, N, J, CLASS, ETA, gs, ss)
}

#' Simulate a DINA Model's \eqn{\eta} Matrix
#'
#' Generates a DINA model's \eqn{\eta} matrix based on alphas and
#' the \eqn{\mathbf{Q}} matrix.
#' @inheritParams sim_dina
#' @author Steven Andrew Culpepper and James Joseph Balamuta
#' @template sim-dina-example-body
#' @export
sim_dina_attributes <- function(alphas, Q) {
    .Call(`_simcdm_sim_dina_attributes`, alphas, Q)
}

#' Simulation Responses from the DINA model
#'
#' Sample responses from the DINA model for given attribute profiles, Q matrix,
#' and item parmeters. Returns a `matrix` of dichotomous responses
#' generated under DINA model.
#'
#' @param alphas A \eqn{N} by K `matrix` of latent attributes.
#' @param Q      A \eqn{N} by K `matrix` indicating which skills are required
#'               for which items.
#' @param ss     A \eqn{J} `vector` of item slipping parameters.
#' @param gs     A \eqn{J} `vector` of item guessing parameters.
#'
#' @return A \eqn{N} by \eqn{J} `matrix` of responses from the DINA model.
#' @author Steven Andrew Culpepper and James Joseph Balamuta
#' @template sim-dina-example-body
#' @export
sim_dina <- function(alphas, Q, ss, gs) {
    .Call(`_simcdm_sim_dina`, alphas, Q, ss, gs)
}

sim_rrum_main <- function(Q, rstar, pistar, alpha) {
    .Call(`_simcdm_sim_rrum_main`, Q, rstar, pistar, alpha)
}

#' Generate data from the rRUM
#'
#' Randomly generate response data according to the reduced Reparameterized
#' Unified Model (rRUM).
#'
#' @param Q      A `matrix` with \eqn{J} rows and \eqn{K} columns indicating
#'               which attributes are required to answer each of the items,
#'               where \eqn{J} represents the number of items and \eqn{K} the
#'               number of attributes.  An entry of 1 indicates attribute
#'               \eqn{k} is required to answer item \eqn{j}.  An entry of one
#'               indicates attribute \eqn{k} is not required.
#' @param rstar  A `matrix` a matrix with \eqn{J} rows and \eqn{K} columns
#'               indicating the penalties for failing to have each of the
#'               required attributes, where \eqn{J} represents the number of
#'               items and \eqn{K} the number of attributes. `rstar` and `Q`
#'               must share the same 0 entries.
#' @param pistar A `vector` of length \eqn{J} indicating the probabiliies of
#'               answering each item correctly for individuals who do not lack
#'               any required attribute, where \eqn{J} represents the number
#'               of items.
#' @param alpha  A `matrix` with \eqn{N} rows and \eqn{K} columns indicating
#'               the subjects attribute acquisition, where \eqn{K} represents
#'               the number of attributes.  An entry of 1 indicates individual
#'               \eqn{i} has attained attribute \eqn{k}. An entry of 0
#'               indicates the attribute has not been attained.
#'
#' @return Y     A `matrix` with \eqn{N} rows and \eqn{J} columns indicating
#'               the indviduals' responses to each of the items, where \eqn{J}
#'               represents the number of items.
#' @author Steven Andrew Culpepper and James Joseph Balamuta
#' @export
#' @template rrum-example
#' @template rrum-references
sim_rrum <- function(Q, rstar, pistar, alpha) {
    .Call(`_simcdm_sim_rrum`, Q, rstar, pistar, alpha)
}

#' Bijection Vector
#'
#' Computes the powers of 2 from \eqn{0} up to \eqn{K - 1}.
#' @param K  Number of Attributes.
#' @return A \code{vec} with length \eqn{K} detailing the power's of 2.
#' @examples
#'
#' bijectionvector(3)
#'
#' @export
bijectionvector <- function(K) {
    .Call(`_simcdm_bijectionvector`, K)
}

#' Perform an Inverse Bijection of an Integer to Attribute Pattern
#'
#' Convert integer between \eqn{0} and \eqn{2^{K-1}} to
#' \eqn{K}-dimensional attribute pattern.
#'
#' @param CL An `integer` between \eqn{0} and \eqn{2^{K-1}}
#' @inheritParams bijectionvector
#' @return A \eqn{K}-dimensional vector with an attribute pattern corresponding
#' to `CL`.
#' @export
#'
#' @examples
#' inv_bijectionvector(5, 1)
#' inv_bijectionvector(5, 2)
inv_bijectionvector <- function(K, CL) {
    .Call(`_simcdm_inv_bijectionvector`, K, CL)
}

#' Generate random Q matrix
#'
#' Simulates a Q matrix containing three identity matrices after a row
#' permutation.
#'
#' @param J Number of Items
#' @param K Number of Attributes
#'
#' @return A dichotomous \code{matrix} for Q.
#' @examples
#' sim_q_matrix(7, 2)
#' 
#' sim_q_matrix(10, 3)
#' @export
sim_q_matrix <- function(J, K) {
    .Call(`_simcdm_sim_q_matrix`, J, K)
}

#' Generate ideal response \eqn{\eta} Matrix
#'
#' Creates the ideal response matrix for each trait
#'
#' @param K      Number of Attribute Levels
#' @param J      Number of Assessment Items
#' @param Q      Q Matrix with dimensions \eqn{K \times J}{K x J}.
#' @return A `mat` with dimensions \eqn{J \times 2^K}{J x 2^K}.
#' @export
#'
#' @examples
#' # Fixed Number of Assessment Items for Q
#' J = 18
#'
#' # Fixed Number of Attributes for Q
#' K       = 3
#' 
#' # Specify Q
#' qbj = c(4, 2, 1, 4, 2, 1, 4, 2, 1, 6, 5, 3, 6, 5, 3, 7, 7, 7)
#'
#' # Fill Q Matrix
#' Q = matrix(, J, K)
#' for (j in seq_len(J)) {
#'   Q[j,] = inv_bijectionvector(K, qbj[j])
#' }
#' 
#' # Create an eta matrix
#' ETA = eta_matrix(K, J, Q)
eta_matrix <- function(K, J, Q) {
    .Call(`_simcdm_eta_matrix`, K, J, Q)
#' Simulate the Latent Attribute Profile Matrix \eqn{\mathbf{\alpha}_c}
#'
#' Generate the \eqn{\mathbf{\alpha}_c = (\alpha_{c1}, \ldots, \alpha_{cK})'} 
#' attribute profile matrix for members of class \eqn{c} such that \eqn{\alpha_{ck}}
#' is 1 if members of class \eqn{c} possess skill \eqn{k} and zero otherwise.
#'
#' @param K Number of Skills
#'
#' @return A \eqn{2^K} by \eqn{K} `matrix` of latent classes
#' corresponding to entry \eqn{c} of \eqn{pi} based upon 
#' mastery and nonmastery of the \eqn{K} skills.
#' 
#' @author James Joseph Balamuta and Steven Andrew Culpepper
#' 
#' @export
#' 
#' @examples
#' # Define test parameters and traits
#' K = 3
#' 
#' # Generate an Latent Attribute Profile (Alpha) Matrix
#' alphas = sim_alpha_matrix(K)
sim_alpha_matrix <- function(K) {
    .Call(`_simcdm_sim_alpha_matrix`, K)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_simcdm_RcppExport_registerCCallable', PACKAGE = 'simcdm')
})
